### PR TITLE
fix flakes for kind

### PR DESCRIPTION
**Pull request by kannon92**
Fixes: #59

### CODE REVIEW

**Comment by klueska** [comment]
I manually triggered a rerun of the test from this PR and it immediately failed:
https://github.com/kubernetes-sigs/dra-example-driver/actions/runs/10777322778/job/29913129778

**Comment by kannon92** [comment]
@klueska (or @bart0sh or @pohly) could one of you try trigger a few runs of these actions to see if this solves the flakes?

**Comment by bart0sh** [comment]
@kannon92 
> No presubmit jobs available for kubernetes-sigs/dra-example-driver@main
>
> Details
> In response to https://github.com/kubernetes-sigs/dra-example-driver/pull/60#issuecomment-2343176326:
>
> /test e2e

Do you happen to know how to configure `presubmit jobs` so they can be restarted this way?

**Comment by bart0sh** [comment]
@kannon92 
> could one of you try trigger a few runs of these actions to see if this solves the flakes?

Triggered it 3-4 times. So far so good.

**Comment by kannon92** [comment]
@bart0sh this is a github action not a presubmit. So you should be able to go to the job and rerun via the UI if you have write permissions.

**Comment by klueska** [comment]
I ran it a few times as well. Seems much more stable now. Thanks.

/approve
/lgtm

**Pull request merged**
