### PR TITLE
[golangci-lint][goimports] add local imports check

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by tariq1890** [comment]
cc @pohly

**Review by pohly — COMMENTED** [review]
I remember that you also had some code changes for import statements. Are those not needed to pass the reconfigured linter check?

**Comment by tariq1890** [comment]
@pohly yes that is correct. I chose to exclude them this time as they are auto-generated code. I believe golangci-lint skips them by default. 

Ideally, kube builder should be generating goimports compliant code

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
