### PR TITLE
Add elezar as approver

### PR DESCRIPTION
**Pull request by elezar**

### CODE REVIEW

**Comment by bart0sh** [comment]
@elezar do you happen to know why do-not-merg/invalid-owners-file label is set?

**Comment by bart0sh** [comment]
found it:
```
elezar
User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.
```

**Comment by elezar** [comment]
Yes, I will have a look at what's required for org membership next week. Happy to leave this open until I get that sorted out.

**Comment by elezar** [comment]
I have created https://github.com/kubernetes/org/issues/4472. If that gets approved, I will retrigger this one.

**Comment by elezar** [comment]
Since https://github.com/kubernetes/org/issues/4472 has been addressed, could we look at merging this?

**Comment by klueska** [comment]
This seems to be blocked with:
> Pending — Not mergeable. Should not have do-not-merge/invalid-owners-file label.

Can you try closing this and opening a new PR? Mabye something got messed up since you weren't yet an org member when you opened it.

**Comment by klueska** [comment]
/remove-do-not-merge/invalid-owners-file

**Pull request merged**
