### PR TITLE
Update to K8s 1.27

### PR DESCRIPTION
**Pull request by byako**

### CODE REVIEW

**Comment by klueska** [comment]
It looks like 1.27.1 is already out. Should we bump to that instead?

**Comment by byako** [comment]
Yep, will do, didn't even think it would be so fast.

**Comment by byako** [comment]
But not so fast, 1.27.1 was release one hour ago, so packages like https://pkg.go.dev/k8s.io/api?tab=versions will be available in couple of hours. I'll update it then.

**Pull request merged**
